### ISSUE TITLE
Cannot send MIDI start/stop

### ISSUE THREAD

**Issue by vjx** [DieterVDW/arduino-midi-clock#8]
I have a button connected to A1 and a 10k resistor on an arduino uno. Testing with the AnalogReadVoltage example I get 1023 when I push the button but with arduino-midi-clock it doesnt send start/stop. Nothing happens.

I am kind of new to electronics so probably I am doing something wrong, can you help please?

Cheers,

**Comment by vjx** [comment]
I solved it by changing line 223 to:
boolean startStopPressed = (START_STOP_PIN_POLARITY + analogRead(START_STOP_INPUT_PIN)) > 1024 / 2 ? true : false;

**Comment by DieterVDW** [comment]
Sorry for the late reply, I've been quite busy!

Have you tried changing the START_STOP_PIN_POLARITY value to 1024 instead of 0?
That will probably have the same effect.

I introduced a lot of parameters to allow configuration and flexibility in the code. However that doesn't make the code very clear, for which I apologise!

I'll close this for now, if you have any extra questions, let me know!
